server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://api:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Request-ID $request_id;
        proxy_set_header X-Actor $http_x_actor;
        proxy_set_header X-Role $http_x_role;
    }

    location /healthz {
        proxy_pass http://api:8080/healthz;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}

